---
# Handlers for redpanda_logging role

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart redpanda
  ansible.builtin.systemd:
    name: redpanda
    state: restarted
  become: true
