---
- name: Ensure basearch is defined
  ansible.builtin.assert:
    that:
      - basearch != ''
    fail_msg: "Variable 'basearch' must be defined! This is equivalent to basearch (which can be gotten with uname -m) on the target system"

- name: Ensure redpanda_version is defined
  ansible.builtin.assert:
    that:
      - redpanda_version != ''
    fail_msg: "Variable 'redpanda_version' must be defined! Don't use latest here, it won't work"

- name: Ensure rpm_or_deb is defined
  ansible.builtin.assert:
    that:
      - rpm_or_deb != ''
    fail_msg: "Variable 'rpm_or_deb' must be defined!"

- name: Bundle RPM
  ansible.builtin.include_tasks: rpm_bundle.yml
  when: rpm_or_deb == "rpm"

- name: Bundle DEB
  ansible.builtin.include_tasks: deb_bundle.yml
  when: rpm_or_deb == "deb"
