---
- name: Set Redpanda RPM
  set_fact:
    rp_standard_rpm_actual: "{{ is_using_unstable | bool | ternary(rp_standard_rpm_unstable, rp_standard_rpm) }}"
    rp_noarch_rpm_actual: "{{ is_using_unstable | bool | ternary(rp_noarch_rpm_unstable, rp_noarch_rpm) }}"
    rp_source_rpm_actual: "{{ is_using_unstable | bool | ternary(rp_source_rpm_unstable, rp_source_rpm) }}"
  tags:
    - airgap-tarball-install

- name: Download Redpanda RPMs to local machine
  ansible.builtin.get_url:
    url: "{{ item.value }}"
    dest: "{{ download_directory }}/{{ item.key }}.rpm"
  loop: "{{ rp_rpm_urls | dict2items }}"
  delegate_to: localhost
  vars:
    rp_rpm_urls:
      rp_standard: "{{ rp_standard_rpm_actual }}"
      rp_noarch: "{{ rp_noarch_rpm_actual }}"
      rp_source: "{{ rp_source_rpm_actual }}"
  tags:
    - airgap-tarball-install

- name: Create tarball of Redpanda RPMs
  ansible.builtin.archive:
    path: "{{ download_directory }}/rp_*.rpm"
    dest: "{{ download_directory }}/redpanda_rpms.tar.gz"
    format: gz
    remove: true
  delegate_to: localhost
  tags:
    - airgap-tarball-install
