- name: Max user instances
  ansible.posix.sysctl:
    name: fs.inotify.max_user_instances
    value: "{{ max_user_instances }}"
    sysctl_set: true
    state: present
    reload: true
  become: true

- name: Set kernel panic on oops
  ansible.posix.sysctl:
    name: kernel.panic_on_oops
    value: "{{ kernel_panic_on_oops }}"
    sysctl_set: true
    state: present
    reload: true
  become: true
