- name: Create redpanda group
  ansible.builtin.group:
    name: "{{ redpanda_group }}"
    state: present
    system: true
  become: true

- name: Create redpanda user
  ansible.builtin.user:
    name: "{{ redpanda_user }}"
    group: "{{ redpanda_group }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: false
    state: present
  become: true
