- name: Install redpanda console (deb)
  ansible.builtin.package:
    name:
      - redpanda-console
    state: "{{ redpanda_install_status }}"
    update_cache: true
  environment:
    https_proxy: "{{ https_proxy_value | default('') }}"
    http_proxy: "{{ https_proxy_value | default('') }}"
  when: https_proxy_value is defined and https_proxy_value | length > 0

- name: Install redpanda console (deb)
  ansible.builtin.package:
    name:
      - redpanda-console
    state: "{{ redpanda_install_status }}"
    update_cache: true
  when: https_proxy_value is not defined or https_proxy_value | length == 0
