# ensure that systemd starts up redpanda console; restarts on change are the
# job of the "Reload systemd and restart console" handler, not this task
- name: Start redpanda console
  ansible.builtin.systemd:
    name: redpanda-console
    state: started
  become: true
