---
galaxy_info:
  author: Redpanda Data DevEx Team
  description: Prepare hosts for Redpanda - data volume discovery and mounting, prerequisite packages, service user
  company: Redpanda Data
  license: Apache-2.0
  min_ansible_version: "2.18"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - redpanda
    - kafka
    - streaming

dependencies: []
