- name: Create Redpanda group
  ansible.builtin.group:
    name: redpanda
    state: present
    system: true
  become: true

- name: Create Redpanda user
  ansible.builtin.user:
    name: redpanda
    group: redpanda
    state: present
    system: true
  become: true
