---
- name: Check if VM is in GCP
  uri:
    url: "http://metadata.google.internal/computeMetadata/v1/instance/id"
    headers:
      Metadata-Flavor: "Google"
    method: GET
    timeout: 10
    validate_certs: no
    status_code: 200
    return_content: no
  register: gcp_metadata
  ignore_errors: yes

- name: Set fact if in GCP
  set_fact:
    using_gcp: true
  when: gcp_metadata.status == 200

- name: Node dependencies - Set APT proxy
  template:
    src: apt_proxy.j2
    dest: /etc/apt/apt.conf.d/proxy.conf
    mode: 0644
  become: true
  when:
    - https_proxy_value is defined and https_proxy_value | length > 0
    - (create_pkg_mgr_proxy | default(false)) is true
    - (using_gcp | default(false)) is false

- name: Node dependencies - update packages - debian
  tags:
    - node_deps
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
  environment:
    https_proxy: "{{ https_proxy_value | default('') }}"

- name: Node dependencies - Install Debian prerequisites
  tags:
    - node_deps
  package:
    name: "{{ debian_prerequisite_packages }}"
    state: present
    update_cache: yes
  environment:
    https_proxy: "{{ https_proxy_value | default('') }}"
