---
# creates service accounts for schema registry and http proxy (25.3+ only)

- name: Create Schema Registry service account
  ansible.builtin.command:
    cmd: >
      rpk security user create {{ schema_registry_service_user }}
      --password {{ schema_registry_service_password }}
      --mechanism SCRAM-SHA-256
      {{ redpanda_rpk_kafka_opts }}
  run_once: true
  when:
    - not is_initialized
    - kafka_enable_authorization | bool
    - sasl_use_explicit_service_accounts | default(true) | bool
  no_log: false

- name: Grant Schema Registry service account permissions
  ansible.builtin.command:
    cmd: >
      rpk security acl create
      --allow-principal User:{{ schema_registry_service_user }}
      --operation all
      --topic '*'
      --cluster
      {{ redpanda_rpk_kafka_opts }}
  run_once: true
  when:
    - not is_initialized
    - kafka_enable_authorization | bool
    - sasl_use_explicit_service_accounts | default(true) | bool
  no_log: false

- name: Create Pandaproxy service account
  ansible.builtin.command:
    cmd: >
      rpk security user create {{ pandaproxy_service_user }}
      --password {{ pandaproxy_service_password }}
      --mechanism SCRAM-SHA-256
      {{ redpanda_rpk_kafka_opts }}
  run_once: true
  when:
    - not is_initialized
    - kafka_enable_authorization | bool
    - sasl_use_explicit_service_accounts | default(true) | bool
  no_log: false

- name: Grant Pandaproxy service account permissions
  ansible.builtin.command:
    cmd: >
      rpk security acl create
      --allow-principal User:{{ pandaproxy_service_user }}
      --operation all
      --topic '*'
      --cluster
      {{ redpanda_rpk_kafka_opts }}
  run_once: true
  when:
    - not is_initialized
    - kafka_enable_authorization | bool
    - sasl_use_explicit_service_accounts | default(true) | bool
  no_log: false
