---
# creates service accounts for schema registry and http proxy (25.3+ only)

- name: Create Schema Registry service account
  ansible.builtin.shell:
    cmd: >
      rpk security user create {{ schema_registry_service_user }}
      --password "$SERVICE_PASSWORD"
      --mechanism SCRAM-SHA-256
      {{ redpanda_rpk_kafka_opts }}
  environment:
    SERVICE_PASSWORD: "{{ schema_registry_service_password }}"
    RPK_USER: "{{ sasl_superuser_username }}"
    RPK_PASS: "{{ sasl_superuser_password }}"
  run_once: true
  when:
    - not is_initialized
    - kafka_enable_authorization | bool
    - sasl_use_explicit_service_accounts | default(true) | bool
  no_log: "{{ redpanda_broker_no_log }}"

- name: Grant Schema Registry service account permissions
  ansible.builtin.shell:
    cmd: >
      rpk security acl create
      --allow-principal User:{{ schema_registry_service_user }}
      --operation all
      --topic '*'
      --cluster
      {{ redpanda_rpk_kafka_opts }}
  environment:
    RPK_USER: "{{ sasl_superuser_username }}"
    RPK_PASS: "{{ sasl_superuser_password }}"
  run_once: true
  when:
    - not is_initialized
    - kafka_enable_authorization | bool
    - sasl_use_explicit_service_accounts | default(true) | bool
  no_log: "{{ redpanda_broker_no_log }}"

- name: Create Pandaproxy service account
  ansible.builtin.shell:
    cmd: >
      rpk security user create {{ pandaproxy_service_user }}
      --password "$SERVICE_PASSWORD"
      --mechanism SCRAM-SHA-256
      {{ redpanda_rpk_kafka_opts }}
  environment:
    SERVICE_PASSWORD: "{{ pandaproxy_service_password }}"
    RPK_USER: "{{ sasl_superuser_username }}"
    RPK_PASS: "{{ sasl_superuser_password }}"
  run_once: true
  when:
    - not is_initialized
    - kafka_enable_authorization | bool
    - sasl_use_explicit_service_accounts | default(true) | bool
  no_log: "{{ redpanda_broker_no_log }}"

- name: Grant Pandaproxy service account permissions
  ansible.builtin.shell:
    cmd: >
      rpk security acl create
      --allow-principal User:{{ pandaproxy_service_user }}
      --operation all
      --topic '*'
      --cluster
      {{ redpanda_rpk_kafka_opts }}
  environment:
    RPK_USER: "{{ sasl_superuser_username }}"
    RPK_PASS: "{{ sasl_superuser_password }}"
  run_once: true
  when:
    - not is_initialized
    - kafka_enable_authorization | bool
    - sasl_use_explicit_service_accounts | default(true) | bool
  no_log: "{{ redpanda_broker_no_log }}"
