---
- name: Check OS FIPS mode with /usr/bin/fips-mode-setup
  ansible.builtin.command:
    cmd: /usr/bin/fips-mode-setup --is-enabled
  register: os_fips_mode
  when:
    - ansible_os_family == "RedHat"
  changed_when: false
  failed_when:
    - os_fips_mode.rc not in fips_check_exit_codes

- name: Ensure OS FIPS state matches the requested fips_mode
  ansible.builtin.assert:
    that:
      - fips_mode != "enabled" or os_fips_mode.rc == 0
    fail_msg: "OS does not have FIPS correctly enabled (fips-mode-setup exit code == {{os_fips_mode.rc}}) while Redpanda Ansible 'fips_mode' is set to {{fips_mode}}; this will cause Redpanda startup failures. set fips_mode=permissive for unsafe bypass"
  when:
    - ansible_os_family == "RedHat"

