---
- name: Set custom fact based on ansible_system_vendor
  set_fact:
    using_gcp: true
  when: ansible_system_vendor == 'Google'

- name: Set fact for package name
  set_fact:
    redpanda_package_name: "redpanda{{ '' if redpanda_version=='latest' else ('=' if ansible_os_family == 'Debian' else '-') + redpanda_version }}"

- name: Install redpanda from repository (Proxy)
  ansible.builtin.package:
    name:
      - "{{ redpanda_package_name }}"
    state: "{{ redpanda_install_status }}"
    update_cache: true
  environment:
    https_proxy: "{{ https_proxy_value | default('') }}"
    http_proxy: "{{ https_proxy_value | default('') }}"
  when:
    - https_proxy_value is defined
    - https_proxy_value | length > 0
    - (using_gcp | default(false)) is false

- name: Install redpanda from repository (Standard)
  ansible.builtin.package:
    name:
      - "{{ redpanda_package_name }}"
    state: "{{ redpanda_install_status }}"
    update_cache: true
  when: https_proxy_value is not defined and (using_gcp | default(false)) is false

- name: Install redpanda from repository (GCP)
  ansible.builtin.package:
    name:
      - "{{ redpanda_package_name }}"
    state: "{{ redpanda_install_status }}"
    update_cache: true
    allow_unauthenticated: yes
  when: (using_gcp | default(false)) is not false


- name: Set data dir file perms
  ansible.builtin.file:
    path: "{{ redpanda_data_directory }}"
    owner: redpanda
    group: redpanda
