---
- name: Set distribution-specific variables
  set_fact:
    distro: "{{ ansible_distribution | lower }}"
    codename: "{{ ansible_distribution_version }}"
    arch: "{{ ansible_architecture }}"

- name: Install yum-utils
  dnf:
    name: yum-utils
    state: present

- name: Import Cloudsmith GPG key
  rpm_key:
    key: "{{ cloudsmith_gpg_key_url }}"
    state: present

- name: Download repository configuration
  get_url:
    url: "{{ cloudsmith_config_url_rpm }}?distro={{ distro }}&codename={{ codename }}"
    dest: /tmp/redpanda-redpanda-nightly.repo
    mode: '0644'
  become: true

- name: Add repository configuration
  command: dnf config-manager --add-repo '/tmp/redpanda-redpanda-nightly.repo'
  become: true

- name: Make DNF cache
  command: dnf -q makecache -y --disablerepo='*' --enablerepo='redpanda-redpanda-nightly' --enablerepo='redpanda-redpanda-nightly-source'
  become: true
