---
- name: Set facts
  ansible.builtin.set_fact:
    keystores_file: tls/certs/{{ansible_hostname}}/{{ keystores_file_name}}
  delegate_to: localhost
  tags: copy_truststore

- name: Ensure /etc/redpanda/keystores exists
  ansible.builtin.file:
    path: "{{ redpanda_keystores_dir }}"
    state: directory
    owner: redpanda
    group: redpanda
    mode: "0755"
  tags: copy_truststore

- name: Check if keystores file exists
  stat:
    path: "{{ keystores_file }}"
  register: keystores_file_stat

- name: Copy keystore to remote hosts in connect group
  ansible.builtin.copy:
      src: "{{ keystores_file }}"
      dest: "{{ redpanda_keystores_dir }}/{{ keystores_file_name }}"
      owner: redpanda
      group: redpanda
      mode: "0644"
  tags: copy_truststore
  when: keystores_file_stat.stat.exists

- name: Create the keystore with a self-signed certificate
  ansible.builtin.command:
    cmd: |
      openssl {{ ssl_keystore_type | lower }} -export -in {{ redpanda_cert_file }} -inkey {{ redpanda_key_file }} -out {{ ssl_keystore_location }} -name {{ ansible_hostname }} -password pass:{{ ssl_keystore_password }}
  tags: generate_keystore
  when: not keystores_file_stat.stat.exists

- name: Ensure /etc/redpanda/keystores exists
  ansible.builtin.file:
    path: "{{ ssl_keystore_location }}"
    state: file
    owner: redpanda
    group: redpanda
    mode: "0755"
  tags: copy_truststore
  when: not keystores_file_stat.stat.exists
