# example usage in a playbook
# log4j_config_override_content: |
#  log4j.rootLogger=INFO, stdout, syslogAppender
#
#  log4j.appender.stdout=org.apache.log4j.ConsoleAppender
#  log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
#
#  log4j.appender.syslogAppender=org.apache.log4j.net.SyslogAppender
#  log4j.appender.syslogAppender.syslogHost=localhost
#  log4j.appender.syslogAppender.facility=LOCAL0
#  log4j.appender.syslogAppender.layout=org.apache.log4j.PatternLayout
#
#  connect.log.pattern=[%d] %p %X{connector.context}%m (%c:%L)%n
#
#  log4j.appender.stdout.layout.ConversionPattern=${connect.log.pattern}
#  log4j.appender.syslogAppender.layout.ConversionPattern=${connect.log.pattern}
#
#  log4j.logger.org.reflections=ERROR

- name: Use user-provided logging config content if defined
  ansible.builtin.copy:
    content: "{{ log4j_config_override_content }}"
    dest: "{{ redpanda_connect_config_dir }}/connect-log4j.properties"
    owner: "{{ redpanda_user }}"
    group: "{{ redpanda_group }}"
    mode: '0644'
    force: true
  when: log4j_config_override_content is defined
  register: log4j_user_config_result

- name: Use default logging config if user-provided content is not defined
  ansible.builtin.template:
    src: log4j.properties.j2
    dest: "{{ redpanda_connect_config_dir }}/connect-log4j.properties"
    owner: "{{ redpanda_user }}"
    group: "{{ redpanda_group }}"
    mode: '0644'
    force: true
  when: log4j_config_override_content is not defined
  register: log4j_default_config_result
